### ISSUE TITLE
Can't kill created terminals

### ISSUE THREAD

**Issue by ceuk** [kortina/run-in-terminal#34] opened 2021-05-03 00:10 UTC
Hey, the trash icons doesn't kill the terminal instance created by this extension, nor does typing `exit`. Is there a way to kill the shell after the command has executed?

e.g. currently a command like this:

`curl http://some-site | less  && exit` will work as intended (i.e. it will open the site content in less and then run exit when you quit less). But as soon as that happens, a new terminal is launched. I would expect it to stay closed (and for the panel to close if there were no more active terminals)

**Comment by JCKodel** [comment] 2023-03-04 16:40
Same here. For some reason, it opens 2 or 3 `run-in-terminal` terminals. When I click on the trash bin to close it, it spawns some others. If I insist, it consumes 100% CPU and freezes VSCode.

**Comment by kortina** [comment] 2023-03-08 01:37
Hmm, not totally sure what is causing this behavior. If anyone has ideas on the root cause or fix, please add context and feel free to submit a PR.

I seem to be able to intermittently duplicate by creating the following file, making it executable, and running it:

```python
#!/usr/bin/env python
import time
time.sleep(10.0)
```

Sometimes (I can't tell exactly when and when not) upon doing this, when I click the Trash icon, it just creates another terminal instead of closing the existing terminal.

**Comment by Lopol2010** [comment] 2023-03-31 04:36
@kortina review my bugfix pls https://github.com/kortina/run-in-terminal/pull/41

**Closed as completed** 2023-03-31 20:28 UTC
Labels: help wanted
